# Transposable Element Next Generation Sequencing

## About
genomics tools for TE-enriched next generation sequencing and detection of active transposable elements  

1. molecular genomics protocol for generating TE-enriched NGS libraries 
2. computational pipeline for detecting TE insertions 

TE calling algorithm consists of two principle steps:  
(i) clustering on genomic coordinates  
(ii) annotation via comparison to public and local TE databases  

## Implementation  
TE-NGS is implemented in R and distributed using [packrat](https://github.com/rstudio/packrat) for management of packages, dependencies, etc. The snapshot is built on R version 3.1.2.  

Tool employing the following packages:  
- Rsamtools for bam manipulation  
- GenomicRanges for manipulation of genomic coordinates  
- Biostrings for fast implementation of regular expression pattern matching  
- data.table for binary search   

The R script requires the following inputs:
- seq_opt_table.txt # a file describing the experimental conditions per sample, eg sample ID, index, primer  
- path to bam directory # a directory containing bam(s) generated by TE-NGS workflow  
- cluster distance (bp) # minimum distance required between neighboring genomic clusters, 201 recommended  
- mode # one of [test,sample] indicating the run mode: test to generate TE calls on NA12878 bams provided in /test; sample for generating TE calls on new sample  

## Getting started  

Navigate to /scripts where packrat snapshot is built  
    $ cd scripts

First time running R, packrat will build the local library of required packages and dependencies bundled in /packrat/src  
launch R

ensure packrat is on  

    > packrat::on()

Check that packrat is up to date 
 
    > packrat::status()

Run the script to generate TE calls  
    
    $ R --no-restore --no-save --no-readline --quiet < R_get_TE_calls_v0.1.r --args ../test/ ../test/seq_opt_table.txt 201 test


## Distribution
Along with the source code are additional files
/annotations
	polyTEdb - an extensive local database of polymorhic TE compiled from public databases and TE protocols (list references)

/examples
Contains example output files
        NA12878_TE-NGS_calls_annotated_v0.1.bed # all TE calls made for NA12878 and results described in manuscript


## Read more
- paper describing method [pdf](#)

- detailed procedures [protocol](#)

- get the source [code](https://github.com/ekviky/TE-NGS)

- email

- other [projects](https://ekviky.github.io/about/)
